// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 12.0.0.0
//  
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Template
{
    using System.Linq;
    using System.Text;
    using System.IO;
    using System.Data;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OI\Documents\git\Git\T4_dropbox\T4_BackEnd\T4_sample\CodeGenerator\Template\ModelTemp.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class ModelTemp : ModelTempBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing Syste" +
                    "m.Text;\r\nusing System.Threading.Tasks;\r\n\r\nnamespace ");
            
            #line 18 "C:\Users\OI\Documents\git\Git\T4_dropbox\T4_BackEnd\T4_sample\CodeGenerator\Template\ModelTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NameSpace));
            
            #line default
            #line hidden
            this.Write(".Model.Domain\r\n{\r\n");
            
            #line 20 "C:\Users\OI\Documents\git\Git\T4_dropbox\T4_BackEnd\T4_sample\CodeGenerator\Template\ModelTemp.tt"
//修改connection string
			string connectionString = "Server=localhost;Database="+DbName+";Trusted_Connection=true"; 
			SqlConnection conn = new SqlConnection(connectionString); 
			conn.Open(); 			
			//如果需要database中全部table，則使用conn.GetSchema("Tables")即可
			string[] restrictions = new string[4];
			restrictions[1] = "dbo";
			//修改table名稱
			restrictions[2] = TableName;
			DataTable schema = conn.GetSchema("Tables", restrictions);			
			string selectQuery = "select * from  @tableName"; 
			SqlCommand command = new SqlCommand(selectQuery,conn); 
			SqlDataAdapter ad = new SqlDataAdapter(command); 
			System.Data.DataSet ds = new DataSet(); 			
			foreach(System.Data.DataRow row in schema.Rows) 
			{
            
            #line default
            #line hidden
            this.Write("    public class ");
            
            #line 36 "C:\Users\OI\Documents\git\Git\T4_dropbox\T4_BackEnd\T4_sample\CodeGenerator\Template\ModelTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(row["TABLE_NAME"].ToString().Trim('s')));
            
            #line default
            #line hidden
            this.Write("Model\r\n    {\r\n");
            
            #line 38 "C:\Users\OI\Documents\git\Git\T4_dropbox\T4_BackEnd\T4_sample\CodeGenerator\Template\ModelTemp.tt"
command.CommandText = selectQuery.Replace("@tableName",row["TABLE_NAME"].ToString()); 
				  ad.FillSchema(ds, SchemaType.Mapped, row["TABLE_NAME"].ToString());

				  foreach (DataColumn dc in ds.Tables[0].Columns)
				  {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 44 "C:\Users\OI\Documents\git\Git\T4_dropbox\T4_BackEnd\T4_sample\CodeGenerator\Template\ModelTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dc.DataType.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 44 "C:\Users\OI\Documents\git\Git\T4_dropbox\T4_BackEnd\T4_sample\CodeGenerator\Template\ModelTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dc.ColumnName));
            
            #line default
            #line hidden
            this.Write("  { get; set; }\r\n");
            
            #line 45 "C:\Users\OI\Documents\git\Git\T4_dropbox\T4_BackEnd\T4_sample\CodeGenerator\Template\ModelTemp.tt"
}
            
            #line default
            #line hidden
            this.Write("                                \r\n    }\r\n");
            
            #line 47 "C:\Users\OI\Documents\git\Git\T4_dropbox\T4_BackEnd\T4_sample\CodeGenerator\Template\ModelTemp.tt"
}
            
            #line default
            #line hidden
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\OI\Documents\git\Git\T4_dropbox\T4_BackEnd\T4_sample\CodeGenerator\Template\ModelTemp.tt"

private string _NameSpaceField;

/// <summary>
/// Access the NameSpace parameter of the template.
/// </summary>
private string NameSpace
{
    get
    {
        return this._NameSpaceField;
    }
}

private string _DbNameField;

/// <summary>
/// Access the DbName parameter of the template.
/// </summary>
private string DbName
{
    get
    {
        return this._DbNameField;
    }
}

private string _TableNameField;

/// <summary>
/// Access the TableName parameter of the template.
/// </summary>
private string TableName
{
    get
    {
        return this._TableNameField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool NameSpaceValueAcquired = false;
if (this.Session.ContainsKey("NameSpace"))
{
    this._NameSpaceField = ((string)(this.Session["NameSpace"]));
    NameSpaceValueAcquired = true;
}
if ((NameSpaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("NameSpace");
    if ((data != null))
    {
        this._NameSpaceField = ((string)(data));
    }
}
bool DbNameValueAcquired = false;
if (this.Session.ContainsKey("DbName"))
{
    this._DbNameField = ((string)(this.Session["DbName"]));
    DbNameValueAcquired = true;
}
if ((DbNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("DbName");
    if ((data != null))
    {
        this._DbNameField = ((string)(data));
    }
}
bool TableNameValueAcquired = false;
if (this.Session.ContainsKey("TableName"))
{
    this._TableNameField = ((string)(this.Session["TableName"]));
    TableNameValueAcquired = true;
}
if ((TableNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("TableName");
    if ((data != null))
    {
        this._TableNameField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class ModelTempBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
